Repository Workiva/workiva_analysis_options, pull requests merged in 2022-09, with the labels that each got.

#180 Fix v2.recommended importing v1 instead of v2
  lib/v2.recommended.yaml
Labels: RM Ready, semver: Patch

#181 Promote invalid_export_of_internal_element to warning
  lib/v2.yaml
Labels: RM Ready, semver: Patch

#182 FEDX-8 Last tweaks for v2 rulesets
  CHANGELOG.md
  LICENSE
  NOTICE
  README.md
  lib/v2.recommended.yaml
  lib/v2.yaml
Labels: RM Ready, semver: Minor

#197 RM-145443 Release workiva_analysis_options 1.3.0
  pubspec.yaml
Labels: RM Ready
